FROM digibib/koha:latest

MAINTAINER Oslo Public Library "digitalutvikling@gmail.com"
ENV REFRESHED_AT 2015-04-21

#########################
# KOHA INSTANCE VARIABLES
#########################

ENV KOHA_ADMINUSER admin
ENV KOHA_ADMINPASS secret
ENV KOHA_INSTANCE name
ENV KOHA_ZEBRAUSER zebrauser
ENV KOHA_ZEBRAPASS lkjasdpoiqrr

WORKDIR /koha/
ENV HOME /koha

EXPOSE 8081

COPY docker-entrypoint.sh /koha/entrypoint.sh
ENTRYPOINT ["/koha/entrypoint.sh"]

# Script for checking if koha is up & ready (to be executed using docker exec)
COPY docker-wait_until_ready.py /koha/wait_until_ready.py