FROM java:openjdk-8-jdk

VOLUME /services/build/libs

COPY . /services

WORKDIR /services

# Install gradlew and cache dependencies
RUN ./gradlew --no-daemon dependencies

RUN ./gradlew --no-daemon build oneJar