PREFIX : <__ONTOLOGY__>

CONSTRUCT { <__GENREURI__> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> :Genre ;
  :prefLabel ?prefLabel ;
  :specification ?specification ;
  :alternativeName ?alternativeName .
}

WHERE {
        { <__GENREURI__> a :Genre }
  UNION { <__GENREURI__> :prefLabel ?prefLabel }
  UNION { <__GENREURI__> :specification ?specification }
  UNION { <__GENREURI__> :alternativeName ?alternativeName }
}
