PREFIX  :     <__ONTOLOGY__>

CONSTRUCT {
  ?eventUri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> :Event ;
            :prefLabel ?label ;
            :specification ?specification ;
            :ordinal ?ordinal ;
            :date ?date .
}

WHERE {
  BIND(uri("__EVENTURI__") AS ?eventUri)
  ?eventUri a :Event .
  OPTIONAL { ?eventUri :prefLabel ?label }
  OPTIONAL { ?eventUri :specification ?specification }
  OPTIONAL { ?eventUri :ordinal ?ordinal }
  OPTIONAL { ?eventUri :date ?date }
}
