PREFIX : <__ONTOLOGY__>

CONSTRUCT {
  <__SUBJECTURI__> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> :Subject ;
    :prefLabel ?prefLabel ;
    :specification ?specification ;
    :alternativeName  ?alternativeName .
}

WHERE {
        { <__SUBJECTURI__>  a :Subject }
  UNION { <__SUBJECTURI__> :prefLabel ?prefLabel }
  UNION { <__SUBJECTURI__> :specification ?specification }
  UNION { <__SUBJECTURI__> :alternativeName  ?alternativeName }
}
