PREFIX : <__ONTOLOGY__>

CONSTRUCT {
  <__EVENTURI__> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> :Event ;
    :prefLabel ?label ;
    :specification ?specification ;
    :ordinal ?ordinal ;
    :date ?date ;
    :alternativeName  ?alternativeName ;
    :placePrefLabel ?placePrefLabel ;
    :placeAlternativeName ?placeAlternativeName .
}

WHERE {
        { <__EVENTURI__> a :Event }
  UNION { <__EVENTURI__> :prefLabel ?label }
  UNION { <__EVENTURI__> :alternativeName ?alternativeName }
  UNION { <__EVENTURI__> :specification ?specification }
  UNION { <__EVENTURI__> :ordinal ?ordinal }
  UNION { <__EVENTURI__> :date ?date }
  UNION { <__EVENTURI__>  :place  ?placeUri .
          ?placeUri a :Place ;
            :prefLabel ?placePrefLabel.
          OPTIONAL { ?placeUri :alternativeName ?placeAlternativeName }
    }
}
