PREFIX : <__ONTOLOGY__>

CONSTRUCT {
  <__WORKSERIESURI__> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> :WorkSeries ;
  :mainTitle ?mainTitle ;
  :subtitle ?subtitle ;
  :partTitle ?partTitle ;
  :partNumber ?partNumber .
}

WHERE {
        { <__WORKSERIESURI__> a :WorkSeries }
  UNION { <__WORKSERIESURI__> :mainTitle ?mainTitle }
  UNION { <__WORKSERIESURI__> :subtitle ?subtitle }
  UNION { <__WORKSERIESURI__> :partTitle ?partTitle }
  UNION { <__WORKSERIESURI__> :partNumber ?partNumber }
}
