PREFIX : <__ONTOLOGY__>

CONSTRUCT {
  <__COMPOSITIONTYPEURI__> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> :CompositionType ;
	  :prefLabel ?label ;
	  :specification ?specification ;
	  :alternativeName  ?alternativeName .
}

WHERE {
        { <__COMPOSITIONTYPEURI__> a :CompositionType }
  UNION { <__COMPOSITIONTYPEURI__> :prefLabel ?label }
  UNION { <__COMPOSITIONTYPEURI__> :specification ?specification }
  UNION { <__COMPOSITIONTYPEURI__> :alternativeName  ?alternativeName }
}
