PREFIX  :     <__ONTOLOGY__>

CONSTRUCT
  { ?workSeriesUri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> :WorkSeries ;
                    :mainTitle ?mainTitle ;
                    :subtitle ?subtitle ;
                    :partTitle ?partTitle ;
                    :partNumber ?partNumber .
  }
WHERE
  { SELECT DISTINCT  ?workSeriesUri ?mainTitle ?subtitle ?partTitle ?partNumber
    WHERE
      { BIND(uri("__WORKSERIESURI__") AS ?workSeriesUri)
        ?workSeriesUri  a                   :WorkSeries ;

        OPTIONAL
          { ?workSeriesUri  :mainTitle  ?mainTitle
          }
        OPTIONAL
          { ?workSeriesUri  :subtitle  ?subtitle
          }
        OPTIONAL
          { ?workSeriesUri  :partTitle  ?partTitle
          }
        OPTIONAL
          { ?workSeriesUri  :partNumber ?partNumber
          }
      }
  }