PREFIX  :     <__ONTOLOGY__>

CONSTRUCT
  { ?genreUri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> :Genre ;
        :prefLabel ?prefLabel ;
        :specification  ?specification ;
        :alternativeName  ?alternativeName .
  }
WHERE
  { SELECT DISTINCT  ?genreUri ?prefLabel ?specification ?alternativeName
    WHERE
      { BIND(uri("__GENREURI__") AS ?genreUri)
        ?genreUri a :Genre ;

        OPTIONAL
          { ?genreUri  :prefLabel  ?prefLabel
          }
        OPTIONAL
          { ?genreUri  :specification  ?specification
          }
        OPTIONAL
          { ?genreUri  :alternativeName  ?alternativeName .
          }
      }
  }