PREFIX  :     <__ONTOLOGY__>

CONSTRUCT
  { ?placeOfPublicationUri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> :PlaceOfPublication .
    ?placeOfPublicationUri :place ?place .
    ?placeOfPublicationUri :country ?country .
  }
WHERE
  { SELECT DISTINCT  ?placeOfPublicationUri ?place ?country
    WHERE
      { BIND(uri("__PLACEOFPUBLICATIONURI__") AS ?placeOfPublicationUri)
        ?placeOfPublicationUri  a                   :PlaceOfPublication ;

        OPTIONAL
          { ?placeOfPublicationUri  :place  ?place
          }

          OPTIONAL
          { ?placeOfPublicationUri  :country  ?country
          }
      }
  }

