PREFIX  :     <__ONTOLOGY__>

CONSTRUCT {
  ?eventUri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> :Event ;
            :prefLabel ?label ;
            :specification ?specification ;
            :ordinal ?ordinal ;
            :date ?date ;
            :alternativeName  ?alternativeName ;
            :placePrefLabel ?placePrefLabel ;
            :placeAlternativeName ?placeAlternativeName .
}

WHERE {
  BIND(uri("__EVENTURI__") AS ?eventUri)
  ?eventUri a :Event .
  OPTIONAL { ?eventUri :prefLabel ?label }
  OPTIONAL { ?eventUri :alternativeName  ?alternativeName }
  OPTIONAL { ?eventUri :specification ?specification }
  OPTIONAL { ?eventUri :ordinal ?ordinal }
  OPTIONAL { ?eventUri :date ?date }
  OPTIONAL
    {
      ?eventUri  :place  ?placeUri .
      ?placeUri a :Place ;
                :prefLabel ?placePrefLabel.
      OPTIONAL {
          ?placeUri :alternativeName ?placeAlternativeName .
      }
    }
}
