PREFIX : <__ONTOLOGY__>

CONSTRUCT {
  <__INSTRUMENTURI__> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> :Instrument ;
		:prefLabel ?label ;
		:specification ?specification ;
		:alternativeName  ?alternativeName .
}

WHERE {
        { <__INSTRUMENTURI__> a :Instrument }
  UNION { <__INSTRUMENTURI__> :prefLabel ?label }
  UNION { <__INSTRUMENTURI__> :specification ?specification }
  UNION { <__INSTRUMENTURI__> :alternativeName ?alternativeName }
}
