PREFIX :     <__ONTOLOGY__>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX duo:  <http://data.man.no/utility#>

CONSTRUCT {
  <__PERSONURI__> a :Person ;
    :name ?name ;
    :birthYear ?birthYear ;
    :deathYear ?deathYear ;
    :ordinal ?ordinal ;
    :specification ?specification ;
    :nationality ?nationalityLabel ;
    :work ?work .
  ?work a :Work ;
    :mainTitle ?mainTitle ;
    :workTypeName ?workTypeName ;
    :partTitle ?partTitle ;
    :partNumber ?partNumber ;
    :subtitle ?subtitle ;
    :publicationYear ?publicationYear ;
    :contribRoleName ?contribRoleName .
}

WHERE {
        { <__PERSONURI__> a :Person }
  UNION { <__PERSONURI__> :name ?name }
  UNION { <__PERSONURI__> :birthYear ?birthYearO . BIND(str(?birthYearO) AS ?birthYear) }
  UNION { <__PERSONURI__> :deathYear ?deathYearO . BIND(str(?deathYearO) AS ?deathYear) }
  UNION { <__PERSONURI__> :ordinal ?ordinalO . BIND(str(?ordinalO) AS ?ordinal) }
  UNION { <__PERSONURI__> :specification ?specificationO . BIND(str(?specificationO) AS ?specification) }
  UNION { <__PERSONURI__> :nationality ?nationality .
          ?nationality rdfs:label ?nl .
          FILTER (lang(?nl) = "no")
          BIND(str(?nl) AS ?nationalityLabel) }
  UNION { ?work a :Work ;
             :contributor ?contrib .
          ?contrib :agent <__PERSONURI__> ;
             :role ?contribRole .
          ?contribRole rdfs:label ?contribRoleNameNo .
          FILTER (lang(?contribRoleNameNo) = "no")
          BIND(str(?contribRoleNameNo) AS ?contribRoleName) }
  UNION { ?work :mainTitle ?mainTitle }
  UNION { ?work :subtitle ?subtitle }
  UNION { ?work :hasWorkType ?hasWorkType .
           ?hasWorkType rdfs:label ?workTypeNameNo .
            FILTER(lang(?workTypeNameNo) = "no")
            BIND(str(?workTypeNameNo) AS ?workTypeName) }
  UNION { ?work :partTitle ?partTitle }
  UNION { ?work :partNumber ?partNumber }
  UNION { ?work :publicationYear ?publicationYearO . BIND(str(?publicationYearO) AS ?publicationYear) }
}
