PREFIX  :     <__ONTOLOGY__>

CONSTRUCT
  { ?corporationUri <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> :Corporation ;
     :name ?name ;
     :subdivision ?subdivision ;
     :specification ?specification ;
     :alternativeName  ?alternativeName .
  }
WHERE
  { SELECT DISTINCT  ?corporationUri ?name ?subdivision ?specification ?alternativeName
    WHERE
      { BIND(uri("__CORPORATIONURI__") AS ?corporationUri)
        ?corporationUri  a                   :Corporation ;

        OPTIONAL
          { ?corporationUri  :name  ?name
          }
        OPTIONAL
          { ?corporationUri  :subdivision  ?subdivision
          }
        OPTIONAL
          { ?corporationUri  :specification  ?specification
          }
        OPTIONAL
          { ?corporationUri  :alternativeName  ?alternativeName
          }
      }
  }