PREFIX : <__ONTOLOGY__>

CONSTRUCT {
  <__CORPORATIONURI__> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> :Corporation ;
    :name ?name ;
    :subdivision ?subdivision ;
    :specification ?specification ;
    :alternativeName ?alternativeName ;
    :placePrefLabel ?placePrefLabel ;
    :placeAlternativeName ?placeAlternativeName .
}

WHERE {
        { <__CORPORATIONURI__> a :Corporation }
  UNION { <__CORPORATIONURI__> :name  ?name }
  UNION { <__CORPORATIONURI__> :subdivision ?subdivision }
  UNION { <__CORPORATIONURI__> :specification ?specification }
  UNION { <__CORPORATIONURI__> :alternativeName ?alternativeName }
  UNION { <__CORPORATIONURI__> :place ?placeUri .
          ?placeUri a :Place ;
            :prefLabel ?placePrefLabel .
          OPTIONAL { ?placeUri :alternativeName ?placeAlternativeName }
      }
}
