FROM node:0.10

MAINTAINER Oslo Public Library "digitalutvikling@gmail.com"
ENV REFRESHED_AT 2015-07-03

RUN npm install -g mocha
RUN npm install -g karma
RUN npm install -g karma-phantomjs-launcher
RUN npm install -g karma-mocha
RUN npm install -g karma-chai
RUN npm install -g chai
RUN npm install -g sinon
RUN npm install -g karma-sinon
RUN npm install -g karma-sinon
RUN npm install -g karma-sinon-chai
RUN npm install -g jscs
RUN npm install -g jshint
RUN npm install -g casperjs

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/

RUN npm install express

VOLUME /usr/src/app/
WORKDIR /usr/src/app/