FROM node:4.2.1

ENV REFRESHED_AT 2015-10-27

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/

RUN npm config set loglevel warn
RUN npm install -g mocha
RUN npm install -g mocha-jsdom
RUN npm install -g chai
RUN npm install -g sinon
RUN npm install -g jscs
RUN npm install -g jshint

COPY . /usr/src/app

VOLUME /usr/src/app/
