FROM node:0.10

MAINTAINER Oslo Public Library "digitalutvikling@gmail.com"
ENV REFRESHED_AT 2015-07-03

RUN npm install -g jslint
RUN npm install -g mocha
RUN npm install -g browserify

RUN mkdir -p /usr/src/app
COPY package.json /usr/src/
WORKDIR /usr/src/

VOLUME /usr/src/app/
WORKDIR /usr/src/app/