FROM node:4.1.1

ENV REFRESHED_AT 2015-10-06

RUN mkdir -p /usr/src/app/public
ADD package.json /usr/src/
ADD public/search.js /usr/src/app/public/
WORKDIR /usr/src/
RUN npm install >npm.log 2>&1
RUN npm run browserify -- app/public/search.js -o app/public/bundle.js

WORKDIR /usr/src/app/

CMD [ "npm", "start" ]
EXPOSE 8000