FROM node:9.11.1

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
COPY .eslintrc /usr/src/app/

RUN npm set progress=false
RUN npm set color=false
RUN npm install > install.log 2>&1

COPY . /usr/src/app
EXPOSE 8000

CMD [ "npm", "run", "productionbuild"]
