export const REQUEST_SEARCH = 'REQUEST_SEARCH'
export const RECEIVE_SEARCH = 'RECEIVE_SEARCH'
export const SEARCH_FAILURE = 'SEARCH_FAILURE'

export const REQUEST_RESOURCE = 'REQUEST_RESOURCE'
export const RECEIVE_RESOURCE = 'RECEIVE_RESOURCE'
export const RESOURCE_FAILURE = 'RESOURCE_FAILURE'

export const REQUEST_TRANSLATION = 'REQUEST_TRANSLATION'
export const RECEIVE_TRANSLATION = 'RECEIVE_TRANSLATION'
export const TRANSLATION_FAILURE = 'TRANSLATION_FAILURE'

