export const REQUEST_SEARCH = 'REQUEST_SEARCH'
export const RECEIVE_SEARCH = 'RECEIVE_SEARCH'
export const SEARCH_FAILURE = 'SEARCH_FAILURE'

export const REQUEST_RESOURCE = 'REQUEST_RESOURCE'
export const RECEIVE_RESOURCE = 'RECEIVE_RESOURCE'
export const RESOURCE_FAILURE = 'RESOURCE_FAILURE'

export const REQUEST_TRANSLATION = 'REQUEST_TRANSLATION'
export const RECEIVE_TRANSLATION = 'RECEIVE_TRANSLATION'
export const TRANSLATION_FAILURE = 'TRANSLATION_FAILURE'

export const SHOW_LOGIN_DIALOG = 'SHOW_LOGIN_DIALOG'
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const REQUEST_LOGIN_STATUS = 'REQUEST_LOGIN_STATUS'
export const RECEIVE_LOGIN_STATUS = 'RECEIVE_LOGIN_STATUS'
export const LOGIN_STATUS_FAILURE = 'LOGIN_STATUS_FAILURE'

export const REQUEST_RESERVE_PUBLICATION = 'REQUEST_RESERVE_PUBLICATION'
export const RESERVE_PUBLICATION_SUCCESS = 'RESERVE_PUBLICATION_SUCCESS'
export const RESERVE_PUBLICATION_FAILURE = 'RESERVE_PUBLICATION_FAILURE'

export const HIDE_MODAL = 'HIDE_MODAL'
export const SHOW_MODAL = 'SHOW_MODAL'
