export const REQUEST_SEARCH = 'REQUEST_SEARCH'
export const FETCH_SEARCH = 'FETCH_SEARCH'
export const RECEIVE_SEARCH = 'RECEIVE_SEARCH'
export const SEARCH_FAILURE = 'SEARCH_FAILURE'

export const REQUEST_RESOURCE = 'REQUEST_RESOURCE'
export const FETCH_RESOURCE = 'FETCH_RESOURCE'
export const RECEIVE_RESOURCE = 'RECEIVE_RESOURCE'
export const RESOURCE_FAILURE = 'RESOURCE_FAILURE'
