export default {
  POSTPONE_RESERVATION: 'POSTPONE_RESERVATION',
  CANCEL_RESERVATION: 'CANCEL_RESERVATION',
  LOGIN: 'LOGIN',
  REGISTRATION: 'REGISTRATION',
  RESERVATION: 'RESERVATION',
  REMOTE_RESERVATION: 'REMOTE_RESERVATION'
}
