export default {
  POSTPONE_RESERVATION: 'POSTPONE_RESERVATION',
  CANCEL_RESERVATION: 'CANCEL_RESERVATION',
  LOGIN: 'LOGIN',
  REGISTRATION: 'REGISTRATION',
  RESERVATION: 'RESERVATION',
  REMOTE_RESERVATION: 'REMOTE_RESERVATION',
  USER_HISTORY: 'USER_HISTORY',
  NEW_USER_OPT_IN_HISTORY: 'NEW_USER_OPT_IN_HISTORY'
}
