INSERT IGNORE INTO branches
  (branchcode, branchname)
VALUES
  ("api","Intern API-avdeling"),
  ("fbje","Bjerke"),
  ("fbjo","Bjørnholt"),
  ("fbol","Bøler"),
  ("ffur","Furuset"),
  ("fgam","Tøyen"),
  ("fgry","Grünerløkka"),
  ("fhol","Holmlia"),
  ("flam","Lambertseter"),
  ("fmaj","Majorstuen"),
  ("fnor","Nordtvet"),
  ("fnyd","Nydalen"),
  ("fopp","Oppsal"),
  ("frik","Rikshospitalet"),
  ("frmm","Rommen"),
  ("froa","Røa"),
  ("from","Romsås"),
  ("fsme","Smestad"),
  ("fsto","Stovner"),
  ("ftor","Torshov"),
  ("hbar","Hovedbiblioteket, barn"),
  ("hsko","Skoletjenesten"),
  ("hutl","Hovedbiblioteket, voksen"),
  ("hvmu","Hovedbiblioteket, musikk"),
  ("ukjent","Ukjent avdeling");
