FROM node:5.6.0

ENV REFRESHED_AT 2016-02-10T08:58

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
COPY .jscsrc /usr/src/app/
COPY .jshintrc /usr/src/app/
COPY .babelrc /usr/src/app/

RUN npm install > install.log 2>&1
VOLUME /usr/src/app/client
VOLUME /usr/src/app/public
VOLUME /usr/src/app/server

EXPOSE 8010

CMD [ "npm", "start" ]