const Constants = require('../../frontend/constants/Constants')

module.exports = {
  queryDefaults: {
    size: 100
  },
  defaultAggregates: {
    facets: {
      global: {},
      aggs: {}
    }
  },
  defaultFields: [
    'actor^20',
    'agents^10',
    'author^50',
    'bio',
    'composer^20',
    'compType',
    'country',
    'desc',
    'director^40',
    'ean',
    'editor^20',
    'format',
    'genre^15',
    'inst',
    'isbn',
    'ismn',
    'language',
    'litform',
    'mainTitle^50',
    'mt',
    'partNumber',
    'partTitle',
    'performer^20',
    'publishedBy',
    'recordId',
    'series^20',
    'subject^50',
    'summary',
    'title^20',
    'workMainTitle',
    'workPartNumber',
    'workPartTitle',
    'workSubtitle'
  ],
  defaultPublicationFields: [
    'agents^10',
    'author^50',
    'country',
    'desc',
    'ean',
    'format',
    'inst',
    'isbn',
    'ismn',
    'language',
    'mainTitle^50',
    'mt',
    'partNumber',
    'partTitle',
    'publishedBy',
    'recordId',
    'series^20',
    'summary',
    'title^20'
  ],
  defaultWorkFields: [
    'agents^0',
    'author^50',
    'bio',
    'compType',
    'country',
    'desc',
    'genre',
    'inst',
    'language',
    'litform',
    'mainTitle',
    'mt',
    'partNumber',
    'partTitle',
    'subtitle',
    'series^10',
    'subject^50',
    'summary',
    'title^20'
  ]
}
