# 1) Slett transkriberte tittler fra DFB-poster, slik at bare den i originaltegnsett gjenstår.

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX raw: <http://data.deichman.no/raw#>

WITH <http://deichman.no/migration>


DELETE {
  ?doc :mainTitle ?transcribedTitle .
}

INSERT {
  ?doc raw:transcribedTitle ?transcribedTitle
}

WHERE {
  ?doc migration:untranscribedTitle ?untranscribedTitle ;
      :mainTitle ?transcribedTitle .
  FILTER(?transcribedTitle != ?untranscribedTitle)
}

;

# 2) Slett transkriberte subtittler fra DFB-poster, slik at bare den i originaltegnsett gjenstår.

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX raw: <http://data.deichman.no/raw#>

WITH <http://deichman.no/migration>

DELETE {
  ?doc :subtitle ?transcribedSubtitle .
}

INSERT {
  ?doc raw:transcribedSubtitle ?transcribedSubtitle
}

WHERE {
  ?doc migration:untranscribedSubtitle ?untranscribedSubtitle ;
      :subtitle ?transcribedSubtitle .
  FILTER(?transcribedSubtitle != ?untranscribedSubtitle)
}
;


#3) Fjern migrasjonstripler

SPARQL
PREFIX migration: <http://migration.deichman.no/>
WITH <http://deichman.no/migration>
DELETE WHERE {
  ?doc migration:untranscribedTitle ?x .
}
;

SPARQL
PREFIX migration: <http://migration.deichman.no/>
WITH <http://deichman.no/migration>
DELETE WHERE {
  ?doc migration:untranscribedSubtitle ?x .
}
;