# 1) Merge locationCategory code 'a' into locationFormat

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX migration: <http://migration.deichman.no/>

WITH <http://deichman.no/migration>

MODIFY

DELETE { 
  ?publication :locationFormat ?format .
}

INSERT {
  ?publication :locationFormat `concat("a",str(?format))` .
}

WHERE {
  ?publication migration:locationCategory "a" ;
    a :Publication .
  OPTIONAL {?publication :locationFormat ?format .}
}
;


# 2) Add parent titles

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX migration: <http://migration.deichman.no/>

WITH <http://deichman.no/migration>

INSERT {
	?publication :mainTitle ?title .
}

WHERE {
	?publication migration:parentRecordTitle ?title .
	MINUS {?publication :mainTitle ?o .}
}
;


# 3) Add main titles from parent records

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX migration: <http://migration.deichman.no/>

WITH <http://deichman.no/migration>

INSERT {
	?publication :mainTitle ?title .
}

WHERE {
	?publication migration:parentRecordId ?id .
	MINUS {?publication :mainTitle ?o .}
	?parent :recordId ?id ;
		:mainTitle ?title .
}
;
