# 1) Slett emneinnførsler på underavdeling "Fortellinger"

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX migration: <http://migration.deichman.no/>

WITH <http://deichman.no/migration>

DELETE {
    ?doc :subject <http://__HOST__/subject/s5d5e6f8238f801c95965fc013bd51e78> .
}

WHERE {
    ?doc :subject <http://__HOST__/subject/s5d5e6f8238f801c95965fc013bd51e78> ;
        migration:subjectAuthority [migration:subdivision "Fortellinger"] .
    MINUS {
        ?doc migration:subjectAuthority [migration:mainLabel "Fortellinger"] .
    }

}
;


# 2) Slett emneinnførsler på underavdeling "Billedbøker", legg til som litterær form

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX literaryForm: <http://data.deichman.no/literaryForm#>

WITH <http://deichman.no/migration>

MODIFY

DELETE {
    ?doc :subject <http://__HOST__/subject/s741c285aabd20767a411bbf4753e3bb8> .
}

INSERT {
    ?doc :literaryForm literaryForm:pictureBook .
}

WHERE {
    ?doc :subject <http://__HOST__/subject/s741c285aabd20767a411bbf4753e3bb8> ;
        migration:subjectAuthority [migration:subdivision "Billedbøker"] .
    MINUS {
        ?doc migration:subjectAuthority [migration:mainLabel "Billedbøker"] .
    }

}
;


# 3) Slett emneinnførsler på underavdeling "Lærebøker", legg til som litterær form

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX literaryForm: <http://data.deichman.no/literaryForm#>

WITH <http://deichman.no/migration>

MODIFY

DELETE {
    ?doc :subject <http://__HOST__/subject/s14e6c71852435c78053fd20a359c3d76> .
}

INSERT {
    ?doc :literaryForm literaryForm:textBook .
}

WHERE {
    ?doc :subject <http://__HOST__/subject/s14e6c71852435c78053fd20a359c3d76> ;
        migration:subjectAuthority [migration:subdivision "Lærebøker"] .
    MINUS {
        ?doc migration:subjectAuthority [migration:mainLabel "Lærebøker"] .
    }

}
;


# 4) Slett emneinnførsler på underavdeling "Filmer"

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX migration: <http://migration.deichman.no/>

WITH <http://deichman.no/migration>

DELETE {
    ?doc :subject <http://__HOST__/subject/se0b8be8ffba2e9d06835d2f508501be8> .
}

WHERE {
    ?doc :subject <http://__HOST__/subject/se0b8be8ffba2e9d06835d2f508501be8> ;
        migration:subjectAuthority [migration:subdivision "Filmer"] .
    MINUS {
        ?doc migration:subjectAuthority [migration:mainLabel "Filmer"] .
    }

}
;


# 5) Slett emneinnførsler på underavdeling "Ordbøker", legg til som litterær form

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX literaryForm: <http://data.deichman.no/literaryForm#>

WITH <http://deichman.no/migration>

MODIFY

DELETE {
    ?doc :subject <http://__HOST__/subject/s2f778b75bb08bc4f7d6005c34a412e3a> .
}

INSERT {
    ?doc :literaryForm literaryForm:dictionary .
}

WHERE {
    ?doc :subject <http://__HOST__/subject/s2f778b75bb08bc4f7d6005c34a412e3a> ;
        migration:subjectAuthority [migration:subdivision "Ordbøker"] .
    MINUS {
        ?doc migration:subjectAuthority [migration:mainLabel "Ordbøker"] .
    }

}
;


# 6) Slett emneinnførsler på underavdeling "Relasjon"

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX migration: <http://migration.deichman.no/>

WITH <http://deichman.no/migration>

DELETE {
    ?doc :subject <http://__HOST__/subject/s0e3823239c7501b5faff46068ab2acca> .
}

WHERE {
    ?doc :subject <http://__HOST__/subject/s0e3823239c7501b5faff46068ab2acca> ;
        migration:subjectAuthority [migration:subdivision "relasjon"] .
    MINUS {
        ?doc migration:subjectAuthority [migration:mainLabel "relasjon"] .
    }

}
;


# 7) Slett emneinnførsler på underavdeling "Alfabetiske oppslagsbøker", legg til som litterær form

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX literaryForm: <http://data.deichman.no/literaryForm#>

WITH <http://deichman.no/migration>

MODIFY

DELETE {
    ?doc :subject <http://__HOST__/subject/sdd93b08c3cd842ed173439dc0f7f0c7e> .
}

INSERT {
    ?doc :literaryForm literaryForm:referenceWork .
}

WHERE {
    ?doc :subject <http://__HOST__/subject/sdd93b08c3cd842ed173439dc0f7f0c7e> ;
        migration:subjectAuthority [migration:subdivision "Alfabetiske oppslagsbøker"] .
    MINUS {
        ?doc migration:subjectAuthority [migration:mainLabel "Alfabetiske oppslagsbøker"] .
    }

}
;

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX literaryForm: <http://data.deichman.no/literaryForm#>

WITH <http://deichman.no/migration>

MODIFY

DELETE {
    ?doc :subject <http://__HOST__/subject/se3ced0fcf3207239908e7f7c64ed4caf> .
}

INSERT {
    ?doc :literaryForm literaryForm:referenceWork .
}

WHERE {
    ?doc :subject <http://__HOST__/subject/se3ced0fcf3207239908e7f7c64ed4caf> ;
        migration:subjectAuthority [migration:subdivision "Alf. oppslagsbøker"] .
    MINUS {
        ?doc migration:subjectAuthority [migration:mainLabel "Alf. oppslagsbøker"] .
    }

}
;


# 8) Slett emneinnførsler på underavdeling "Artikler m.m."

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX migration: <http://migration.deichman.no/>

WITH <http://deichman.no/migration>

DELETE {
    ?doc :subject <http://__HOST__/subject/s9fa4c007b641947a159efaa335be91a2> .
}

WHERE {
    ?doc :subject <http://__HOST__/subject/s9fa4c007b641947a159efaa335be91a2> ;
        migration:subjectAuthority [migration:subdivision "Artikler m.m."] .
    MINUS {
        ?doc migration:subjectAuthority [migration:mainLabel "Artikler m.m."] .
    }

}
;