# 1) Konstruer emner for motiv i kunsten

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX migration: <http://migration.deichman.no/>

WITH <http://deichman.no/migration>

MODIFY

DELETE {
    ?pub :subject ?sub .
}

INSERT {

    ?pub :subject `IRI(CONCAT(STR("http://data.deichman.no/subject/s"), STR(MD5(CONCAT(STR(?label), " i kunsten")))))` .
    `IRI(CONCAT(STR("http://data.deichman.no/subject/s"), STR(MD5(CONCAT(STR(?label), " i kunsten")))))` :prefLabel `CONCAT(STR(?label), " i kunsten")` ;
    a :Subject .
} WHERE {
    ?aut migration:specification "Motiv" ;
        migration:subdivision "Kunst" ;
        migration:mainLabel ?label .
    ?pub :subject <http://data.deichman.no/subject/s25fd40aa38e2dade45f2cef549cd1efa> ;
        migration:subjectAuthority ?aut ;
        :subject ?sub ;
        a :Publication .
    ?sub :specification "Motiv" ;
        :prefLabel ?label .
}
;


# 2) Konstruer emner for tema i litteraturen

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX migration: <http://migration.deichman.no/>

WITH <http://deichman.no/migration>

MODIFY

DELETE {
    ?pub :subject ?sub .
}

INSERT {
    ?pub :subject `IRI(CONCAT(STR("http://data.deichman.no/subject/s"), STR(MD5(CONCAT(STR(?label), " i litteraturen")))))` .
    `IRI(CONCAT(STR("http://data.deichman.no/subject/s"), STR(MD5(CONCAT(STR(?label), " i litteraturen")))))` :prefLabel `CONCAT(STR(?label), " i litteraturen")` ;
    a :Subject .
} WHERE {
    ?aut migration:specification "Tema" ;
        migration:subdivision "Litteratur" ;
        migration:mainLabel ?label .
    ?pub :subject <http://data.deichman.no/subject/sc4a76e14eeb35d88fa9f97ff9d2be9c0> ;
        migration:subjectAuthority ?aut ;
        :subject ?sub ;
        a :Publication .
    ?sub :specification "Tema" ;
        :prefLabel ?label .
}
;


# 3) Konstruer emner for tema i barnelitteraturen

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX migration: <http://migration.deichman.no/>

WITH <http://deichman.no/migration>

MODIFY

DELETE {
    ?pub :subject ?sub .
}

INSERT {
    ?pub :subject `IRI(CONCAT(STR("http://data.deichman.no/subject/s"), STR(MD5(CONCAT(STR(?label), " i barnelitteraturen")))))` .
    `IRI(CONCAT(STR("http://data.deichman.no/subject/s"), STR(MD5(CONCAT(STR(?label), " i barnelitteraturen")))))` :prefLabel `CONCAT(STR(?label), " i barnelitteraturen")` ;
    a :Subject .
} WHERE {
    ?aut migration:specification "Tema" ;
        migration:subdivision "Barnelitteratur" ;
        migration:mainLabel ?label .
    ?pub :subject <http://data.deichman.no/subject/sf00b6852e4a3a5858afdb394e75504fb> ;
        migration:subjectAuthority ?aut ;
        :subject ?sub ;
        a :Publication .
    ?sub :specification "Tema" ;
        :prefLabel ?label .
}
;


# 4) Konstruer emner for tema i film

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX migration: <http://migration.deichman.no/>

WITH <http://deichman.no/migration>

MODIFY

DELETE {
    ?pub :subject ?sub .
}

INSERT {
    ?pub :subject `IRI(CONCAT(STR("http://data.deichman.no/subject/s"), STR(MD5(CONCAT(STR(?label), " i film")))))` .
    `IRI(CONCAT(STR("http://data.deichman.no/subject/s"), STR(MD5(CONCAT(STR(?label), " i film")))))` :prefLabel `CONCAT(STR(?label), " i film")` ;
    a :Subject .
} WHERE {
    ?aut migration:specification "Tema" ;
        migration:subdivision "Film" ;
        migration:mainLabel ?label .
    ?pub :subject <http://data.deichman.no/subject/sbae9023301664a3ea829a63c67d6f882> ;
        migration:subjectAuthority ?aut ;
        :subject ?sub ;
        a :Publication .
    ?sub :specification "Tema" ;
        :prefLabel ?label .
}
;


# 5) Create places with specification from subdivisions

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX migration: <http://migration.deichman.no/>

WITH <http://deichman.no/migration>

MODIFY

DELETE {
    ?doc :subject `IRI(CONCAT("http://data.deichman.no/subject/s", MD5(?label)))` ;
        :subject `IRI(CONCAT("http://data.deichman.no/subject/s", MD5(?specLabel)))` .
}

INSERT { ?doc :subject `IRI(CONCAT("http://data.deichman.no/place/g", MD5(CONCAT(?label, "_", ?spec))))` . }

WHERE {
    ?geoSubAuth migration:specification ?spec ;
        a migration:SubjectAuthorityM651 ;
        migration:mainLabel ?label .
    ?subAuth migration:subdivision ?label ;
        migration:subdivision ?specLabel .
    FILTER (?specLabel = CONCAT("(", ?spec, ")")) .
    ?doc migration:subjectAuthority ?subAuth ;
        a :Publication .
}
;


# 6) Update places with specification registered as concepts

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>

WITH <http://deichman.no/migration>

MODIFY

DELETE { ?doc :subject ?subject . }
INSERT { ?doc :subject `iri(CONCAT("http://data.deichman.no/place/g", MD5(CONCAT(?label, "_", ?spec))))` . }

WHERE {
    ?geoSubAuth migration:specification ?spec ;
        a migration:SubjectAuthorityM651 ;
        duo:bibliofilAuthorityId ?id .
    ?subAuth duo:bibliofilAuthorityId ?id ;
        a migration:SubjectAuthorityM650 ;
        migration:mainLabel ?label .
    ?doc migration:subjectAuthority ?subAuth ;
        :subject ?subject ;
        a :Publication .
    ?subject :prefLabel ?label ;
        :specification ?spec .
}
;


# 7) Update other places registered as concepts

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>

WITH <http://deichman.no/migration>

MODIFY

DELETE { ?doc :subject ?subject . }
INSERT { ?doc :subject `iri(CONCAT("http://data.deichman.no/place/g", MD5(?label)))` . }

WHERE {
    ?geoAuth a migration:SubjectAuthorityM651 ;
        duo:bibliofilAuthorityId ?id ;
        migration:mainLabel ?label .
    MINUS {?geoAuth migration:specification ?spec .}
    ?subAuth duo:bibliofilAuthorityId ?id ;
        a migration:SubjectAuthorityM650 .
    ?doc migration:subjectAuthority ?subAuth ;
        :subject ?subject ;
        a :Publication .
    ?subject :prefLabel ?label ;
        a :Subject .
}
;
