# 1) Remove split statements from publications

SPARQL
PREFIX migration: <http://migration.deichman.no/>
PREFIX : <http://data.deichman.no/ontology#>

WITH <http://deichman.no/migration>

DELETE {
  ?publication ?p ?o
} WHERE {
  ?publication a :Publication ;
    ?p ?o .
  VALUES ?p {
    migration:genreSplit1
    migration:genreSplit2
    migration:genreSplitMain
    migration:genreSplitSub
  }
}
;


# 2) Biography genres with subdivision

SPARQL
PREFIX migration: <http://migration.deichman.no/>
PREFIX : <http://data.deichman.no/ontology#>
PREFIX literaryForm: <http://data.deichman.no/literaryForm#>
PREFIX duo: <http://data.deichman.no/duo#>

WITH <http://deichman.no/migration>

MODIFY

DELETE {
  ?publication :genre ?genre ;
    migration:genreSplit ?genreSplit .
}

INSERT {
  ?publication :literaryForm literaryForm:biography ;
    :subject `IRI(CONCAT(STR("http://data.deichman.no/subject/s"), STR(MD5(STR(?label)))))` .
  `IRI(CONCAT(STR("http://data.deichman.no/subject/s"), STR(MD5(STR(?label)))))` a :Subject ;
    :prefLabel ?label .
}

WHERE {
  ?genreSplit migration:genreSplitMain <http://data.deichman.no/genre/gf9e7a1a0a6912af8c1227f268ce80be1> ;
    migration:genreSplitSub ?genreSplitSub ;
    duo:bibliofilAuthorityId ?id ;
    a migration:GenreSplit .
  ?genreSplitSub :prefLabel ?label .
  ?publication migration:genreSplit ?genreSplit ;
    :genre ?genre .
  ?genre duo:bibliofilAuthorityId ?id .  
}
;


#3) Form + country of origin split

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>

WITH <http://deichman.no/migration>

MODIFY

DELETE {
 ?publication :genre ?genre ;
  migration:genreSplit ?genreSplit . 
}

INSERT {
  ?publication migration:form ?genreSplit1 ;
    migration:nationOfOrigin ?label .  
}

WHERE {
  ?genreSplit migration:genreSplit1 ?genreSplit1 ;
    migration:genreSplit2 ?genreSplit2 ;
    duo:bibliofilAuthorityId ?id ;
    a migration:GenreSplit .
  ?genre duo:bibliofilAuthorityId ?id .
  ?publication migration:genreSplit ?genreSplit ;
    :genre ?genre .
  ?genreSplit2 :prefLabel ?label .
}
;


# 3b) Construct literaryForms from 3)

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX genre: <http://data.deichman.no/genre/>
PREFIX literaryForm: <http://data.deichman.no/literaryForm#>

WITH <http://deichman.no/migration>

MODIFY

DELETE {
  ?pub migration:form ?old .
}

INSERT {
  ?pub :literaryForm ?form .
}

WHERE {
    ?pub a :Publication ;
         migration:form ?old  .

    VALUES (?old ?form) {
      (genre:g8485f1b48ceda0998652c91ebe113ec7         literaryForm:comicBook)
      (genre:gc22bb0ade4c6cf956780a73f4fe2ae82         literaryForm:movie)
      (genre:g00bbd6c64086b4e701f8fb04c4e0b6fd         literaryForm:animatedMovie)
    }
}
;