# 1) workAuthority for utgivelser med adaptor

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>
PREFIX role: <http://data.deichman.no/role#>

WITH <http://deichman.no/migration>

INSERT {
  ?publication migration:workAuthority ?sum .
}

WHERE {
 { SELECT SUM(xsd:int(?id)) AS ?sum ?publication WHERE {
    ?publication role:adaptor [duo:bibliofilAuthorityId ?id] ;
      a :Publication .
  }}
}
;


# 2) workAuthority for utgivelser med creator

SPARQL
DEFINE sql:log-enable 2
PREFIX : <http://data.deichman.no/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>

WITH <http://deichman.no/migration>

INSERT {
  ?publication migration:workAuthority ?sum .
}

WHERE {
 { SELECT SUM(xsd:int(?id)) AS ?sum ?publication WHERE {
   ?publication migration:creator [duo:bibliofilAuthorityId ?id] ;
      a :Publication .
    MINUS {?publication migration:workAuthority ?o .}
  }}
}
;


# 3) workAuthority for utgivelser med editor

SPARQL
DEFINE sql:log-enable 2
PREFIX : <http://data.deichman.no/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>
PREFIX role: <http://data.deichman.no/role#>

WITH <http://deichman.no/migration>

INSERT {
  ?publication migration:workAuthority ?sum .
}

WHERE {
 { SELECT SUM(xsd:int(?id)) AS ?sum ?publication WHERE {
   ?publication role:editor [duo:bibliofilAuthorityId ?id] ;
      a :Publication .
    MINUS {?publication migration:workAuthority ?o .}
  }}
}
;


# 4) workAuthority for utgivelser med director

SPARQL
DEFINE sql:log-enable 2
PREFIX : <http://data.deichman.no/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>
PREFIX role: <http://data.deichman.no/role#>

WITH <http://deichman.no/migration>

INSERT {
  ?publication migration:workAuthority ?sum .
}

WHERE {
 { SELECT SUM(xsd:int(?id)) AS ?sum ?publication WHERE {
    ?publication role:director [duo:bibliofilAuthorityId ?id] ;
     a :Publication .
    MINUS {?publication migration:workAuthority ?o .}
  }}
}
;


# 5) workAuthority for utgivelser med composer

SPARQL
DEFINE sql:log-enable 2
PREFIX : <http://data.deichman.no/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>
PREFIX role: <http://data.deichman.no/role#>

WITH <http://deichman.no/migration>

INSERT {
  ?publication migration:workAuthority ?sum .
}

WHERE {
 { SELECT SUM(xsd:int(?id)) AS ?sum ?publication WHERE {
    ?publication role:composer [duo:bibliofilAuthorityId ?id] ;
     a :Publication .
    MINUS {?publication migration:workAuthority ?o .}
  }}
}
;


# 6) workAuthority for utgivelser med performer

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>
PREFIX role: <http://data.deichman.no/role#>

WITH <http://deichman.no/migration>

INSERT {
  ?publication migration:workAuthority ?sum .
}

WHERE {
 { SELECT SUM(xsd:int(?id)) AS ?sum ?publication WHERE {
    ?publication role:performer [duo:bibliofilAuthorityId ?id] ;
     a :Publication .
    MINUS {?publication migration:workAuthority ?o .}
  }}
}
;


# 20) Verk fra utgivelser med workAuthority, uten originaltittel

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>

WITH <http://deichman.no/migration>

INSERT {
  `IRI(CONCAT(STR("http://data.deichman.no/work/w"), MD5(LCASE(CONCAT(STR(?workAuthority), ?mainTitle, ?partNumber, ?partTitle)))))` a :Work ;
    :mainTitle ?mainTitle ;
    :partNumber ?partNumber ;
    :partTitle ?partTitle .
  ?publication :publicationOf `IRI(CONCAT(STR("http://data.deichman.no/work/w"), MD5(LCASE(CONCAT(STR(?workAuthority), ?mainTitle, ?partNumber, ?partTitle)))))` .
}

WHERE {
  ?publication migration:workAuthority ?workAuthority ;
    a :Publication ;
    :mainTitle ?mainTitle .
  MINUS { ?publication migration:originalTitle ?originalTitle .}
  OPTIONAL { ?publication :partNumber ?partNumber .}
  OPTIONAL { ?publication :partTitle ?partTitle .}
}
;


# 21) Verk fra utgivelser med workAuthority og originaltittel

SPARQL
DEFINE sql:log-enable 2
PREFIX : <http://data.deichman.no/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>

WITH <http://deichman.no/migration>

INSERT {
  `IRI(CONCAT(STR("http://data.deichman.no/work/w"), MD5(LCASE(CONCAT(STR(?workAuthority), ?mainTitle, ?partNumber, ?partTitle)))))` a :Work ;
    :mainTitle ?mainTitle ;
    :partNumber ?partNumber ;
    :partTitle ?partTitle .
  ?publication :publicationOf `IRI(CONCAT(STR("http://data.deichman.no/work/w"), MD5(LCASE(CONCAT(STR(?workAuthority), ?mainTitle, ?partNumber, ?partTitle)))))` .
}

WHERE {
  ?publication migration:workAuthority ?workAuthority ;
    migration:originalTitle ?mainTitle ;
    a :Publication .
  OPTIONAL { ?publication migration:originalPartNumber ?partNumber .}
  OPTIONAL { ?publication migration:originalPartTitle ?partTitle .}
}
;


# 22) Verk fra utgivelser uten workAuthority og originaltittel

SPARQL
DEFINE sql:log-enable 2
PREFIX : <http://data.deichman.no/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>

WITH <http://deichman.no/migration>

INSERT {
  `IRI(CONCAT(STR("http://data.deichman.no/work/w"), MD5(?recordId)))` a :Work ;
    :mainTitle ?mainTitle ;
    :partNumber ?partNumber ;
    :partTitle ?partTitle .
  ?publication :publicationOf `IRI(CONCAT(STR("http://data.deichman.no/work/w"), MD5(?recordId)))` .
}

WHERE {
  ?publication :mainTitle ?mainTitle ;
    :recordId ?recordId ;
    a :Publication .
  MINUS { ?publication migration:originalTitle ?originalTitle .}
  MINUS { ?publication migration:workAuthority ?workAuthority .}
  OPTIONAL { ?publication :partNumber ?partNumber .}
  OPTIONAL { ?publication :partTitle ?partTitle .}
}
;


# 23) Verk fra utgivelser uten workAuthority, med originaltittel

SPARQL
DEFINE sql:log-enable 2
PREFIX : <http://data.deichman.no/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>

WITH <http://deichman.no/migration>

INSERT {
  `IRI(CONCAT(STR("http://data.deichman.no/work/w"), MD5(?recordId)))` a :Work ;
    :mainTitle ?mainTitle ;
    :partNumber ?partNumber ;
    :partTitle ?partTitle .
  ?publication :publicationOf `IRI(CONCAT(STR("http://data.deichman.no/work/w"), MD5(?recordId)))` .
}

WHERE {
  ?publication migration:originalTitle ?mainTitle ;
    :recordId ?recordId ;
    a :Publication .
  MINUS { ?publication migration:workAuthority ?workAuthority .}
  OPTIONAL { ?publication migration:originalPartNumber ?partNumber .}
  OPTIONAL { ?publication migration:originalPartTitle ?partTitle .}
}
;


# 24) Merge works for parent-child records
# 
# SPARQL
# DEFINE sql:log-enable 2
# PREFIX : <http://data.deichman.no/ontology#>
# PREFIX migration: <http://migration.deichman.no/>
# 
# WITH <http://deichman.no/migration>
# 
# MODIFY
# 
# DELETE {
#   ?child :publicationOf ?childWork .
#   ?childWork ?p ?o .
# }
# 
# INSERT {
#   ?child :publicationOf ?parentWork .
# }
# 
# WHERE {
#   ?child migration:parentRecordId ?parentId ;
#     :publicationOf ?childWork ;
#     :mainTitle ?title .
#   ?parent :recordId ?parentId ;
#     :mainTitle ?title ;
#     :publicationOf ?parentWork .
#   ?childWork ?p ?o .
#   MINUS {
#     ?other :publicationOf ?childWork .
#     FILTER (?other != ?child)
#   }
# }
# ;



# Remove duplicate mainTitle and partTitle from work (result of lowecasing titles for generating work uris)
;
SPARQL
PREFIX : <http://data.deichman.no/ontology#>
WITH <http://deichman.no/migration>
INSERT { ?work :keepMainTitle ?mainTitle }
WHERE {
 SELECT ?work SAMPLE(?title) AS ?mainTitle WHERE {
   ?work a :Work ;
        :mainTitle ?title
  }  GROUP BY ?work
}
;

;
SPARQL
PREFIX : <http://data.deichman.no/ontology#>
WITH <http://deichman.no/migration>
INSERT { ?work :keepPartTitle ?partTitle }
WHERE {
 SELECT ?work SAMPLE(?title) AS ?partTitle WHERE {
   ?work a :Work ;
        :partTitle ?title
  }  GROUP BY ?work
}
;

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
WITH <http://deichman.no/migration>
DELETE { ?work :mainTitle ?mainTitle }
WHERE { ?work a :Work ; :mainTitle ?mainTitle }
;

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
WITH <http://deichman.no/migration>
DELETE { ?work :partTitle ?partTitle }
WHERE { ?work a :Work ; :partTitle ?partTitle }
;

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
WITH <http://deichman.no/migration>
DELETE { ?work :keepMainTitle ?mainTitle }
INSERT { ?work :mainTitle ?mainTitle }
WHERE { ?work :keepMainTitle ?mainTitle }
;

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
WITH <http://deichman.no/migration>
DELETE { ?work :keepPartTitle ?partTitle  }
INSERT { ?work :partTitle ?partTitle }
WHERE { ?work :keepPartTitle ?partTitle }
;
