# 1) workAuthority for utgivelser med creator

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>

WITH <http://deichman.no/migration>

INSERT {
  ?publication migration:workAuthority ?sum .
}

WHERE {
 { SELECT SUM(xsd:int(?id)) AS ?sum ?publication WHERE {
    ?publication migration:creator [duo:bibliofilAuthorityId ?id] ;
      a :Publication .
  }}
}
;


# 2) workAuthority for utgivelser med editor

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>
PREFIX role: <http://data.deichman.no/role#>

WITH <http://deichman.no/migration>

INSERT {
  ?publication migration:workAuthority ?sum .
}

WHERE {
 { SELECT SUM(xsd:int(?id)) AS ?sum ?publication WHERE {
   ?publication role:editor [duo:bibliofilAuthorityId ?id] ;
      a :Publication .
    MINUS {?publication migration:workAuthority ?o .}
  }}
}
;


# 3) workAuthority for utgivelser med director

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>
PREFIX role: <http://data.deichman.no/role#>

WITH <http://deichman.no/migration>

INSERT {
  ?publication migration:workAuthority ?sum .
}

WHERE {
 { SELECT SUM(xsd:int(?id)) AS ?sum ?publication WHERE {
    ?publication role:director [duo:bibliofilAuthorityId ?id] ;
     a :Publication .
    MINUS {?publication migration:workAuthority ?o .}
  }}
}
;


# 4) workAuthority for utgivelser med composer

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>
PREFIX role: <http://data.deichman.no/role#>

WITH <http://deichman.no/migration>

INSERT {
  ?publication migration:workAuthority ?sum .
}

WHERE {
 { SELECT SUM(xsd:int(?id)) AS ?sum ?publication WHERE {
    ?publication role:composer [duo:bibliofilAuthorityId ?id] ;
     a :Publication .
    MINUS {?publication migration:workAuthority ?o .}
  }}
}
;


# 5) workAuthority for utgivelser med performer

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>
PREFIX role: <http://data.deichman.no/role#>

WITH <http://deichman.no/migration>

INSERT {
  ?publication migration:workAuthority ?sum .
}

WHERE {
 { SELECT SUM(xsd:int(?id)) AS ?sum ?publication WHERE {
    ?publication role:performer [duo:bibliofilAuthorityId ?id] ;
     a :Publication .
    MINUS {?publication migration:workAuthority ?o .}
  }}
}
;



# 6) workAuthority for utgivelser med illustrator

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>
PREFIX role: <http://data.deichman.no/role#>

WITH <http://deichman.no/migration>

INSERT {
  ?publication migration:workAuthority ?sum .
}

WHERE {
 { SELECT SUM(xsd:int(?id)) AS ?sum ?publication WHERE {
    ?publication role:illustrator [duo:bibliofilAuthorityId ?id] ;
     a :Publication .
    MINUS {?publication migration:workAuthority ?o .}
  }}
}
;



# 7) workAuthority for utgivelser med publisher

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>
PREFIX role: <http://data.deichman.no/role#>

WITH <http://deichman.no/migration>

INSERT {
  ?publication migration:workAuthority ?sum .
}

WHERE {
 { SELECT SUM(xsd:int(?id)) AS ?sum ?publication WHERE {
    ?publication role:publisher [duo:bibliofilAuthorityId ?id] ;
      a :Publication .
    MINUS {?publication migration:workAuthority ?o .}
  }}
}
;



# 8) workAuthority for utgivelser med contributor

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>
PREFIX role: <http://data.deichman.no/role#>

WITH <http://deichman.no/migration>

INSERT {
  ?publication migration:workAuthority ?sum .
}

WHERE {
 { SELECT SUM(xsd:int(?id)) AS ?sum ?publication WHERE {
    ?publication role:contributor [duo:bibliofilAuthorityId ?id] ;
     a :Publication .
    MINUS {?publication migration:workAuthority ?o .}
  }}
}
;


# 19) Verk fra utgivelser uten originaltittel

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>

WITH <http://deichman.no/migration>

INSERT {
  `IRI(CONCAT(STR("http://__HOST__/work/w"), MD5(LCASE(CONCAT(STR(?workAuthority), ?mainTitle, ?partNumber, ?partTitle)))))` a :Work ;
    :mainTitle ?mainTitle ;
    :partNumber ?partNumber ;
    :partTitle ?partTitle .
  ?publication :publicationOf `IRI(CONCAT(STR("http://__HOST__/work/w"), MD5(LCASE(CONCAT(STR(?workAuthority), ?mainTitle, ?partNumber, ?partTitle)))))` .
}

WHERE {
  ?publication a :Publication ;
    :mainTitle ?mainTitle .
  MINUS { ?publication migration:originalTitle ?originalTitle .}
  OPTIONAL { ?publication migration:workAuthority ?workAuthority .}
  OPTIONAL { ?publication :partNumber ?partNumber .}
  OPTIONAL { ?publication :partTitle ?partTitle .}
}
;


# 20) Verk fra utgivelser med originaltittel

SPARQL
PREFIX : <http://__HOST__/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX duo: <http://data.deichman.no/duo#>

WITH <http://deichman.no/migration>

INSERT {
  `IRI(CONCAT(STR("http://__HOST__/work/w"), MD5(LCASE(CONCAT(STR(?workAuthority), ?mainTitle, ?partNumber, ?partTitle)))))` a :Work ;
    :mainTitle ?mainTitle ;
    :partNumber ?partNumber ;
    :partTitle ?partTitle .
  ?publication :publicationOf `IRI(CONCAT(STR("http://__HOST__/work/w"), MD5(LCASE(CONCAT(STR(?workAuthority), ?mainTitle, ?partNumber, ?partTitle)))))` .
}

WHERE {
  ?publication 
  migration:originalTitle ?mainTitle ;
    a :Publication .
  OPTIONAL { ?publication migration:workAuthority ?workAuthority .}
  OPTIONAL { ?publication migration:originalPartNumber ?partNumber .}
  OPTIONAL { ?publication migration:originalPartTitle ?partTitle .}
}
;


# Remove duplicate mainTitle and partTitle from work (result of lowecasing titles for generating work uris)
;
SPARQL
PREFIX : <http://__HOST__/ontology#>
WITH <http://deichman.no/migration>
INSERT { ?work :keepMainTitle ?mainTitle }
WHERE {
 SELECT ?work SAMPLE(?title) AS ?mainTitle WHERE {
   ?work a :Work ;
        :mainTitle ?title
  }  GROUP BY ?work
}
;

;
SPARQL
PREFIX : <http://__HOST__/ontology#>
WITH <http://deichman.no/migration>
INSERT { ?work :keepPartTitle ?partTitle }
WHERE {
 SELECT ?work SAMPLE(?title) AS ?partTitle WHERE {
   ?work a :Work ;
        :partTitle ?title
  }  GROUP BY ?work
}
;

SPARQL
PREFIX : <http://__HOST__/ontology#>
WITH <http://deichman.no/migration>
DELETE { ?work :mainTitle ?mainTitle }
WHERE { ?work a :Work ; :mainTitle ?mainTitle }
;

SPARQL
PREFIX : <http://__HOST__/ontology#>
WITH <http://deichman.no/migration>
DELETE { ?work :partTitle ?partTitle }
WHERE { ?work a :Work ; :partTitle ?partTitle }
;

SPARQL
PREFIX : <http://__HOST__/ontology#>
WITH <http://deichman.no/migration>
DELETE { ?work :keepMainTitle ?mainTitle }
INSERT { ?work :mainTitle ?mainTitle }
WHERE { ?work :keepMainTitle ?mainTitle }
;

SPARQL
PREFIX : <http://__HOST__/ontology#>
WITH <http://deichman.no/migration>
DELETE { ?work :keepPartTitle ?partTitle  }
INSERT { ?work :partTitle ?partTitle }
WHERE { ?work :keepPartTitle ?partTitle }
;
