# 1) Legg til informasjon fra publication på verk:
SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX role: <http://data.deichman.no/role#>

WITH <http://deichman.no/migration>

INSERT {
	?work ?p ?o .
}

WHERE {
      ?publication :publicationOf ?work ;
                   ?p ?o .
      VALUES ?p { :audience :literaryForm :genre :subject :hasWorkType :hasCompositionType }
}
;


SPARQL
PREFIX : <http://data.deichman.no/ontology#>
WITH <http://deichman.no/migration>
DELETE { ?publication :genre ?o .}
WHERE { ?publication :publicationOf ?work ; :genre ?o }
;

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
WITH <http://deichman.no/migration>
DELETE { ?publication :subject ?o .}
WHERE { ?publication :publicationOf ?work ; :subject ?o }
;

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
WITH <http://deichman.no/migration>
DELETE { ?publication :audience ?o .}
WHERE { ?publication :publicationOf ?work ; :audience ?o }
;

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
WITH <http://deichman.no/migration>
DELETE { ?publication :literaryForm ?o .}
WHERE { ?publication :publicationOf ?work ; :literaryForm ?o }
;

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
WITH <http://deichman.no/migration>
DELETE { ?publication :hasWorkType ?o .}
WHERE { ?publication :publicationOf ?work ; :hasWorkType ?o }
;

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
WITH <http://deichman.no/migration>
DELETE { ?publication :hasCompositionType ?o .}
WHERE { ?publication :publicationOf ?work ; :hasCompositionType ?o }
;

# 2b)
SPARQL
DEFINE sql:log-enable 2
PREFIX : <http://data.deichman.no/ontology#>
PREFIX migration: <http://migration.deichman.no/>

WITH <http://deichman.no/migration>

DELETE {
  ?publication ?p ?o .
}

WHERE {
      ?publication :publicationOf ?work ;
                   ?p ?o .
      VALUES ?p {
            migration:creator
            migration:originalLanguage
            migration:originalTitle
            migration:originalPartTitle
      }
}
;

# 3) Fjern
SPARQL
WITH <http://deichman.no/migration>
DELETE WHERE { ?s ?p <http://lexvo.org/id/iso639-3/mul> }
;
