# 1) Velg minste førsteutgavekandidat som årstall på verk

SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX migration: <http://migration.deichman.no/>
PREFIX raw: <http://data.deichman.no/raw#>

WITH <http://deichman.no/migration>

INSERT {
    ?work :publicationYear ?minYear .
} WHERE {
{
    SELECT ?work MIN(?year) as ?minYear WHERE {
        ?publication raw:firstEditionCandidate ?year ;
            a :Publication ;
                :publicationOf ?work .
    }
}
}
;

# 2) Velg den mainEntryRole som IKKE er author, dersom det er flere ulike som tilhører samme verk
SPARQL
PREFIX : <http://data.deichman.no/ontology#>
PREFIX migration: <http://migration.deichman.no/>
WITH <http://deichman.no/migration>
DELETE { ?pub1 migration:mainEntryRole <http://data.deichman.no/role#author> }
INSERT { ?pub1 migration:mainEntryRole ?role }
WHERE {
	?pub1 :publicationOf ?work ;
		  migration:mainEntryRole <http://data.deichman.no/role#author> .
	?pub2 :publicationOf ?work ;
		  migration:mainEntryRole ?role .
    MINUS { ?pub2 migration:mainEntryRole <http://data.deichman.no/role#author> }
	FILTER(?pub1 != ?pub2)
}
;
