# encoding: UTF-8
require 'csv'
require_relative '../support/services/csvimport/migration.rb'
 
Given(/^at en låner ikke finnes som låner hos biblioteket fra før$/) do
  steps %Q{
    Gitt at det finnes en lånerkategori
    Og at det finnes en avdeling
  }
end

Given(/^at det finnes en lånerkategori$/) do
  steps %Q{
    Når jeg legger til en lånerkategori
  }
end

Given(/^at "(.*?)" eksisterer som en låner$/) do |name|
  steps %Q{
    Gitt at det finnes en lånerkategori
    Når jeg legger inn \"#{name}\" som ny låner
    Så viser systemet at \"#{name}\" er låner
  }
end

Given(/^at det finnes en låner$/) do
  step "at \"Knut\" eksisterer som en låner"
end

Given(/^at det finnes en låner med lånekort$/) do |table|
  step "at det finnes en avdeling"        unless @active[:branch]
  step "jeg legger til en lånerkategori"  unless @active[:patroncategory]

  patrons = table.hashes

  patrons.each do |patron|
    patron[:branchcode] = @active[:branch].code         # Override with autogenerated
    patron[:category]   = @active[:patroncategory].code # Override with autogenerated
    patron = patron.inject({}){|h,(k,v)| h.merge({ k.to_sym => v}) } # Symbolize keys
    user = CSVImport::User.new(@browser,@context,@active).import(patron)

    @active[:patron] = user
    (@context[:patrons] ||= []) << user

    @cleanup.push( "låner #{user.firstname} #{user.surname}" =>
      lambda do
        @site.Patrons.go.delete(user.firstname, user.surname)
      end
    )
  end

end

Given(/^at det finnes data som beskriver en låner$/) do
  @import = File.join(File.dirname(__FILE__), '..', 'upload-files', 'patrons.csv')
end

Given(/^at det finnes en mapping for konvertering$/) do
  @map = File.join(File.dirname(__FILE__), '..', 'upload-files', 'mapping_patrons.csv')
end

Given(/^at det finnes konverterte lånerdata$/) do
  steps %Q{
    Gitt at det finnes en mapping for konvertering
    Når lånerdata migreres
  }
end

Given(/^at jeg har en liste over lånerkategorier$/) do
  @borrower_categories = File.join(File.dirname(__FILE__), '..', 'upload-files', 'borrower_categories.csv')
end

Given(/^at låneren ikke har utestående purregebyr$/) do
  @browser.div(:id => "finesholdsissues").table.should_not be_present
end


Given(/^at låneren ikke er fratatt lånerretten$/) do
  @browser.div(:id => "reldebarments").table.should_not be_present
end

Given(/^at låneren ikke har aktiv innkrevingssak$/) do
  next    # TODO: This function is not implemented yet
  pending # express the regexp above with the code you wish you had
end

When(/^jeg er på administrasjonssiden for lånerkategorier$/) do
  @site.PatronCategories.go
end

When(/^jeg velger å vise alle lånerkategorier$/) do
  @browser.select_list(:name => "table_categorie_length").select_value("-1")
end

Then(/^samsvarer listen i grensesnittet med liste over lånerkategorier$/) do
  rows = @browser.table(:id => "table_categorie").tbody.rows
  orig = []
  rows.each do |row|
    orig << { :categorycode => row[0].text, :description => row[1].text }
  end
  csv = []
  CSV.foreach(@borrower_categories, {
      :headers => true, 
      :encoding => 'UTF-8',
      :header_converters => :symbol
    }) do |c|
      csv << { :categorycode => c[:categorycode], :description => c[:description] }
  end
  # Array comparison
  a = (orig & csv == orig)
  b = (csv & orig == csv)

  a.should == true
  b.should == true

end

When(/^lånerdata migreres$/) do
  @migration = Migration.new(@map, @import)
  step "at det finnes en avdeling"        unless @active[:branch]
  step "jeg legger til en lånerkategori"  unless @active[:patroncategory]

  patron = Patron.new
  patron.branch   = @active[:branch]
  patron.category = @active[:patroncategory]

  # map the first borrower for testing
  patron.cardnumber = @migration.import.keys.first
  id = patron.cardnumber
  @migration.import[id][:cardnumber]   = patron.cardnumber
  @migration.import[id][:surname]      = patron.surname
  @migration.import[id][:categorycode] = patron.category.code
  @migration.import[id][:branchcode]   = patron.branch.code
  @active[:patron] = patron
  (@context[:patrons] ||= []) << patron
end

When(/^lånerdata importeres i admingrensesnittet$/) do
  # import_user_via_csv takes @patron Struct
  CSVImport::User.new(@browser,@context,@active).import(@migration.import[@active[:patron].cardnumber])
  patron = @active[:patron]
  @cleanup.push( "låner #{patron.firstname} #{patron.surname}" =>
    lambda do
      @site.Patrons.go.delete(patron.firstname, patron.surname)
    end
  )
end

When(/^jeg legger til en lånerkategori$/) do
  patroncategory = PatronCategory.new

  @site.PatronCategories.go.create(patroncategory.code, patroncategory.description)

  @active[:patroncategory] = patroncategory
  (@context[:patroncategories] ||= []) << patroncategory

  @cleanup.push( "lånerkategori #{patroncategory.description}" =>
    lambda do
      @site.PatronCategories.go.delete(patroncategory.description)
    end
  )
end

When(/^jeg legger inn "(.*?)" som ny låner$/) do |name|
  patron = Patron.new
  # Branch and PatronCategory are prerequisites
  patron.branch   = @active[:branch]
  patron.category = @active[:patroncategory]

  @site.Patrons.
      go.
      create(patron.category.description,
             name,
             patron.surname,
             "#{name}.#{patron.surname}",
             patron.surname)

  @active[:patron] = patron
  (@context[:patrons] ||= []) << patron
  @cleanup.push( "låner #{name} #{patron.surname}" =>
    lambda do
      @site.Patrons.go.delete(name, patron.surname)
    end
  )
end

Then(/^kan jeg se kategorien i listen over lånerkategorier$/) do
  table = @browser.table(:id => "table_categorie")
  @browser.select_list(:name => "table_categorie_length").select_value("-1")
  table.wait_until_present
  table.text.should include @active[:patroncategory].code
end

Then(/^viser systemet at "(.*?)" er låner$/) do |name|
  fullname = "#{name} #{@active[:patron].surname}"
  patron_details = @site.Home.go.search_patrons fullname
  patron_details.header.should include fullname
  @active[:patron].cardnumber = patron_details.card_number
end

Then(/^samsvarer de migrerte lånerdata med mapping$/) do
  @migration.map.each do |field,map|
    if map[:teststatus] && map[:teststatus].downcase == 'ok'
      @migration.import[@active[:patron].cardnumber].keys.to_s.should include(map[:plassering_i_koha])
    end
  end
end

Then(/^viser systemet at låneren er importert$/) do
  @browser.goto intranet(:patrons)
  @browser.text_field(:id => "searchmember").set @active[:patron].cardnumber
  @browser.form(:action => "/cgi-bin/koha/members/member.pl").submit
  @browser.title.should include @active[:patron].surname
  @browser.link(:id => "editpatron").click
  # iterate patron advanced edit form and check for values
  patronform = @browser.form(:id => "entryform")
  @migration.import[@active[:patron].cardnumber].each do |key,value|
    if value
      case "#{key}"
      when "dateofbirth"
        label = patronform.label(:for => "#{key}")
        label.parent.html.should include(Date.parse(value).strftime("%m/%d/%Y"))
      when "branchcode"
        @browser.select_list(:id => "libraries").selected?(@active[:branch].name).should == true
      when "categorycode"
        @browser.select_list(:id => "categorycode_entry").selected?(@active[:patron].category.description).should == true
      when "smsalertnumber"
        label = patronform.label(:for => "phone")
        label.parent.html.should include(value)
      when "sex","password","fnr","patron_attributes","old_id"
        # TODO
      else
        label = patronform.label(:for => "#{key}")
        label.parent.html.should include(value)
      end
    end
  end
end
