FROM ruby:2.2.1

MAINTAINER Oslo Public Library "digitalutvikling@gmail.com"
ENV REFRESHED_AT 2015-04-08

RUN mkdir -p /usr/src/app/

WORKDIR /usr/src/
COPY Gemfile /usr/src/
RUN bundle install

WORKDIR /usr/src/app/

ENTRYPOINT ["bundle", "exec"]
CMD ["rake", "start"]

EXPOSE 4567
