require 'rake/testtask'

task :default => [:start]

task :start do
  ruby "lib/server.rb"
end

Rake::TestTask.new do |t|
  t.libs << "tests"
  t.test_files = FileList['tests/test*.rb']
  t.verbose = true
end
